### PR TITLE
monki

### PR DESCRIPTION
**Pull request by terranaut1**
## About The Pull Request

adds monkey subtype sechailers for the upcoming winners of the toolbox tournament :)

## Changelog
:cl:Monki
add: Monki
/:cl:

### CODE REVIEW

**Comment by terranaut1** [comment]
ignore the dumb commit name i'm retarded but it worked out in the end

**Comment by tralezab** [comment]
alright cool beans

**Comment by CitrusGender** [comment]
approved by me, he used it last year and he's just pring it this year since it wasn't a simple change.

**Comment by ishitbyabullet** [comment]
closed for not being monke enough

**Pull request merged**
